import Header from "./Header";
import Footer from "../Footer";

import "../../css/ManagePin.css";

import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { fetchDoc } from "../../utils/firebase";

import { useImmer } from "use-immer";
import { collection, doc } from "firebase/firestore";

import GeneratePin from "./GeneratePin";

// function for individual pin
function Pin({ pin }) {
  return (
    <div className="pin">
      <div className="pin-details">
        <p className={`title is-size-4 ${pin.used ? "has-text-success" : ""}`}>
          {pin.id}
        </p>
        <p className="subtitle is-size-6">
          {pin.tag}
          <br />
          Generated by: {pin.vendor}
          <br />
          Retailer: {pin.retailer ? pin.retailer : pin.vendor}
        </p>
        {/* <p>Used at: {new Date(pin.usedAt)}</p> */}
      </div>
      <hr />
      {pin.used && (
        <div className="user-detail">
          {/* it's supposed to be an object... but moving on... */}
          <p>{pin.usedBy.username}</p>
          <p>{pin.usedBy.email}</p>
        </div>
      )}
    </div>
  );
}

function ManagePin() {
  let [pins, setPins] = useState([]);

  useEffect(() => {
    // moving on... search for pin
    fetchDoc("codes").then((c) => {
      setPins(c);
    });
  }, []); // whenever pins changes, the thing should refire
  // this will help when generating pin
  return (
    <div id="manage-pins">
      <Header login={true} from={"pin"} />
      <main>
        <section className="pin-section">
          <ul>
            {pins.map((p) => {
              return <Pin pin={p} />;
            })}
          </ul>
        </section>
        <section className="generate-pin">
            <GeneratePin setPins={setPins}/>
        </section>
      </main>
      <Footer />
    </div>
  );
}

export default ManagePin;
